// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlpvszragcssmncyniyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscHZzenJhZ2Nzc21uY3luaXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTc5MjMsImV4cCI6MjA3MjMzMzkyM30.x6TUM2I5x1z4fw_2I919FcLuQ7A-bQZ5PVo6TcE6JXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});